"""add sources and extend rag_chunks

Revision ID: 5c21106a888c
Revises: 97ba4eed80a8
Create Date: 2026-05-26 09:38:39.191048
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c21106a888c'
down_revision: str | None = '97ba4eed80a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_status'), ['status'], unique=False)

    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('canon_level', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chunk_text', sa.Text(), nullable=True))
        batch_op.create_index('ix_rag_chunks_project', ['project_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_rag_chunks_source_id_sources',
            'sources',
            ['source_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rag_chunks_source_id_sources', type_='foreignkey')
        batch_op.drop_index('ix_rag_chunks_project')
        batch_op.drop_column('chunk_text')
        batch_op.drop_column('metadata')
        batch_op.drop_column('canon_level')
        batch_op.drop_column('source_ref')
        batch_op.drop_column('source_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_status'))
        batch_op.drop_index(batch_op.f('ix_sources_project_id'))

    op.drop_table('sources')
    # ### end Alembic commands ###
