"""initial schema

Revision ID: 97ba4eed80a8
Revises: 
Create Date: 2026-05-19 13:17:04.591336
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97ba4eed80a8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('input_context_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifacts_parent', ['parent_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_artifacts_run_stage', ['run_id', 'stage'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('workflow_node', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_llm_call_logs_project_id'),
            ['project_id'],
            unique=False,
        )
        batch_op.create_index(batch_op.f('ix_llm_call_logs_run_id'), ['run_id'], unique=False)

    op.create_table('rag_chunks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=True),
    sa.Column('chunk_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_chunks_chunk_type'), ['chunk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_source'), ['source'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('current_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('langgraph_thread_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_workflow_runs_project_id'),
            ['project_id'],
            unique=False,
        )

    op.create_table('artifact_commits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_commits', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_artifact_commits_project_id'),
            ['project_id'],
            unique=False,
        )
        batch_op.create_index(batch_op.f('ix_artifact_commits_run_id'), ['run_id'], unique=False)

    op.create_table('audit_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('issues_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_audit_reports_artifact_id'),
            ['artifact_id'],
            unique=False,
        )

    op.create_table('human_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('review_type', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_human_reviews_artifact_id'),
            ['artifact_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_reviews_artifact_id'))

    op.drop_table('human_reviews')
    with op.batch_alter_table('audit_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_reports_artifact_id'))

    op.drop_table('audit_reports')
    with op.batch_alter_table('artifact_commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_commits_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_commits_project_id'))

    op.drop_table('artifact_commits')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_project_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_chunks_source'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_chunk_type'))

    op.drop_table('rag_chunks')
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_run_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_project_id'))

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_run_stage')
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))
        batch_op.drop_index('ix_artifacts_parent')

    op.drop_table('artifacts')
    # ### end Alembic commands ###
